name: Playwright & Pytest Tests

on:
  push:
    branches:
      - main  # Run tests when pushing to the main branch
  pull_request:
    branches:
      - main  # Run tests on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          playwright install

      - name: Run API Tests
        run: |
          pytest tests/tests_be/

      - name: Run UI Tests (Headless)
        run: |
          pytest tests/tests_fe/
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
